Задача 8: Review-service Add likes-dislikes
druzhininyury/yandex-workshop-review-service pull request #7
Opened 2024-11-25 15:46 UTC by KurakinPavel

2024-11-26 05:41 UTC, Hyacintholuscus commented on src/main/java/ru/practicum/workshop/reviewservice/service/ReviewServiceImpl.java
> +            User evaluator = userStorage.findById(evaluatorId).orElseThrow(() -> {
В этом сервисе эти поиск и ошибка не нужны. Пользователи здесь - это id и их имя, которые они указали при создании отзыва на мероприятие. А поставить оценку могут любые авторизованные пользователи, о которых в этом сервисе информации может и не быть

2024-11-26 05:41 UTC, Hyacintholuscus commented on src/main/resources/db/migration/V2__initial_schema.sql
> +    evaluator_id BIGINT REFERENCES users (id) ON DELETE SET NULL,
Связь с таблицей users здесь не нужна

2024-11-26 05:45 UTC, Hyacintholuscus commented on src/main/java/ru/practicum/workshop/reviewservice/service/ReviewServiceImpl.java
> +                if (label.equals(Label.LIKE)) {
Можно улучшить: метод addOpinion получился довольно крупным. Я бы этот блок if-else  выделила в отдельный метод

2024-11-26 05:46 UTC, Hyacintholuscus commented on src/main/java/ru/practicum/workshop/reviewservice/service/ReviewServiceImpl.java
> +            if (label.equals(Label.LIKE)) {
Можно также вынести в отдельный private метод этот блок

2024-11-26 05:52 UTC, Hyacintholuscus commented on src/main/java/ru/practicum/workshop/reviewservice/model/Opinion.java
> +    private User evaluator;
Здесь достаточно просто id пользователя, оценивающего отзыв, так как в БД в этом сервисе сохраняются только пользователи, когда-либо писавшие отзыв

2024-11-26 06:08 UTC, Hyacintholuscus commented on src/main/java/ru/practicum/workshop/reviewservice/controller/ReviewController.java
> +    public void addLike(@RequestHeader("X-Review-User-Id")
Я понимаю, что это учебный проект, но, мне кажется, что можно сделать этот метод не void. А возвращать DTO с получившимся количеством лайков и дизлайков и id review, например.
Но это просто размышления, основываясь на просмотре того, как это работает vk, например

2024-11-26 06:17 UTC, Hyacintholuscus commented on src/main/java/ru/practicum/workshop/reviewservice/storage/OpinionStorage.java
> +    Opinion findOneByReview_IdAndEvaluator_Id(long reviewId, long evaluatorId);
Можно сделать, чтобы этот метод возвращал Optional,  и как минимум при вызове его в методе removeOpinion() можно вызвать метод .orElseThrow() для проброса исключения EntityNotFoundException

2024-11-26 06:22 UTC, Hyacintholuscus commented on src/main/java/ru/practicum/workshop/reviewservice/service/ReviewServiceImpl.java
> +            log.info("Like from user with id={} to review with id={} deleted", evaluatorId, reviewId);
Уменьшение количества лайков и дизлайков с логированиями можно вынести в отдельные private методы, т. к. эти строки используются и в методе по добавлению лайков / дизлайков

2024-11-26 06:25 UTC, Hyacintholuscus commented on src/main/java/ru/practicum/workshop/reviewservice/service/ReviewServiceImpl.java
> +            reviewStorage.save(review);
Сохранение review можно вынести за блоки if-else, т. к. оно в любом случае происходит, если не возникло исключение

2024-11-26 06:29 UTC, Hyacintholuscus commented on src/test/java/ru/practicum/workshop/reviewservice/controller/ReviewControllerTest.java
> +    @Autowired
Хочу понять: уже ведь есть аннотация RequiredArgsConstructor. Для чего отдельно прописывать Autowired? И почему аннотировано только одно поле?

2024-11-26 06:36 UTC, Hyacintholuscus commented on src/test/java/ru/practicum/workshop/reviewservice/service/ReviewServiceImplTest.java
> +        assertEquals(0, review.getLikes());
Лучше не привязываться в тестах к константным значениям. Да, в этом тесте каждый раз создаётся новое review, но, если поменять метод beforeEach на beforeAll, то может возникнуть ошибка в этом тесте, ведь тесты запускаются не в том же порядке, в котором написаны

2024-11-26 06:37 UTC, Hyacintholuscus commented on src/test/java/ru/practicum/workshop/reviewservice/service/ReviewServiceImplTest.java
> +    @DisplayName("Поставить дизлайк отзыву")
Имя этого теста, наверное, должно быть "Удалить дизлайк отзыву"

2024-11-26 06:38 UTC, Hyacintholuscus commented on src/test/java/ru/practicum/workshop/reviewservice/service/ReviewServiceImplTest.java
> +        assertEquals(0, review.getLikes());
Ещё стоит проверить количество дизлайков, что оно не увеличилось

2024-11-26 06:39 UTC, Hyacintholuscus commented on src/test/java/ru/practicum/workshop/reviewservice/service/ReviewServiceImplTest.java
> +        assertEquals(0, review.getDislikes());
Ещё стоит проверить количество лайков, что оно не увеличилось

2024-11-26 06:44 UTC, Hyacintholuscus commented on src/main/java/ru/practicum/workshop/reviewservice/controller/ReviewController.java
> +    public void addDislike(@RequestHeader("X-Review-User-Id")
По поводу заголовков: я их такими написала до нашего обсуждения заголовков. Поэтому можно упростить его и поменять на "X-User-Id", наверное. Здесь ещё нужно мнение Юрия @druzhininyury

2024-11-26 06:47 UTC, Hyacintholuscus commented on src/main/resources/application.properties
> +spring.sql.init.mode=always
Уверен, что здесь нужно поставить always? В default профиле и с never всё работает

2024-11-26 06:49 UTC, Hyacintholuscus commented on src/main/resources/application.properties
> +spring.sql.init.mode=always
БД H2 будет нормально запускаться в профиле test, если после названия БД поставить ;DB_CLOSE_DELAY=-1 
Так это выглядит: 
spring.flyway.url=jdbc:h2:mem:task-service_db;DB_CLOSE_DELAY=-1
при этом spring.sql.init.mode можно оставить never

2024-11-26 06:50 UTC, Hyacintholuscus requested changes
В целом всё хорошо, но есть, на что обратить внимание. В особенности: на комментарии по поводу User в Opnion, на комментарии в тестах сервиса и на комментарии в application.properties

2024-11-26 07:55 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/reviewservice/service/ReviewServiceImpl.java
> +            User evaluator = userStorage.findById(evaluatorId).orElseThrow(() -> {
Да, вижу, что в сервисе реализован свой, "внутренний" user-service (только из-за username?), сохраняющий данные любого пользователя при создании сущности (review). По аналогии, и при постановке лайка / дизлайка нужно  было бы сохранять нового пользователя с каждой новой отметкой.
Возможно, так и нужно, но как тогда review-service будет взаимодействовать с user-service? Подозреваю, что за управление пользователями, которые могут что-то делать в системе, будет "отвечать" именно user-service.

При реализации задачи 8 совместил оба подхода (к одному из которых, думаю, и останется при соединении микросервисов). Данные по юзеру берутся из числа уже сохранённых во "внутреннем" user-service, но нового юзера не сохраняется. 
При этом, при создании сущности (лайка / дизлайка) делается проверка наличия юзера в данных сервиса.

Предлагаю то, что касается юзеров, оставить как оно есть до момента соединения сервисов. А когда будут понятны требования приложения в целом - так и так придётся переделывать.

2024-11-26 07:56 UTC, KurakinPavel commented on src/main/resources/db/migration/V2__initial_schema.sql
> +    evaluator_id BIGINT REFERENCES users (id) ON DELETE SET NULL,
См выше.

2024-11-26 08:05 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/reviewservice/model/Opinion.java
> +    private User evaluator;
См общий ответ выше.

2024-11-26 08:12 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/reviewservice/controller/ReviewController.java
> +    public void addLike(@RequestHeader("X-Review-User-Id")
Предлагаю оставить на следующий этап.

2024-11-26 09:12 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/reviewservice/storage/OpinionStorage.java
> +    Opinion findOneByReview_IdAndEvaluator_Id(long reviewId, long evaluatorId);
Исправлено.

2024-11-26 10:19 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/reviewservice/service/ReviewServiceImpl.java
> +                if (label.equals(Label.LIKE)) {
Добавление (чтобы организовывалось по единой логике) и удаление лайков вытащил в отдельные методы.
После этого метод уменьшился, на страницу умещается. Имхо, если ещё делить на приватные - будет труднее разобраться.

2024-11-26 10:20 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/reviewservice/service/ReviewServiceImpl.java
> +            if (label.equals(Label.LIKE)) {
Исправил.

2024-11-26 10:20 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/reviewservice/service/ReviewServiceImpl.java
> +            log.info("Like from user with id={} to review with id={} deleted", evaluatorId, reviewId);
Исправил.

2024-11-26 10:32 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/reviewservice/service/ReviewServiceImpl.java
> +            reviewStorage.save(review);
Исправил.

2024-11-26 10:50 UTC, KurakinPavel commented on src/test/java/ru/practicum/workshop/reviewservice/controller/ReviewControllerTest.java
> +    @Autowired
Исправил.
Из-за использования ReviewMapperImpl из генерируемых классов тестовый класс помечен, как имеющий ошибки, но всё равно запускается.
Не сразу понял, в чём дело, и аннотация осталась от попыток убрать эту индикацию.

2024-11-26 10:54 UTC, KurakinPavel commented on src/test/java/ru/practicum/workshop/reviewservice/service/ReviewServiceImplTest.java
> +    @DisplayName("Поставить дизлайк отзыву")
Исправил

2024-11-26 11:03 UTC, KurakinPavel commented on src/test/java/ru/practicum/workshop/reviewservice/service/ReviewServiceImplTest.java
> +        assertEquals(0, review.getLikes());
Так у нас проверка идёт на появление / удаление строго определённого количества лайков / дизлайков после обращения к эндпоинтам.
Аналогично в 9-й задаче, к примеру, условие ТЗ "Это правило работает только в том случае, если общее количество лайков и дизлайков больше 10" без использования в тестах константы (10) не проверишь.

2024-11-26 11:06 UTC, KurakinPavel commented on src/test/java/ru/practicum/workshop/reviewservice/service/ReviewServiceImplTest.java
> +        assertEquals(0, review.getLikes());
Исправил.

2024-11-26 11:06 UTC, KurakinPavel commented on src/test/java/ru/practicum/workshop/reviewservice/service/ReviewServiceImplTest.java
> +        assertEquals(0, review.getDislikes());
Исправил.

2024-11-26 11:09 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/reviewservice/controller/ReviewController.java
> +    public void addDislike(@RequestHeader("X-Review-User-Id")
Пока оставлю так. 
Кому править тесты для postman (к которым пока не понимаю, как подступиться), если решим менять - обсудим дополнительно.

2024-11-26 11:40 UTC, KurakinPavel commented on src/main/resources/application.properties
> +spring.sql.init.mode=always
Исправил, с учётом замечания ниже.

2024-11-26 11:51 UTC, KurakinPavel commented on src/main/resources/application.properties
> +spring.sql.init.mode=always
Да, с этой настройкой в тестовом профиле, и везде never всё, действительно, работает.
Поправил.

Но позже всё равно буду разбираться.

2024-11-26 13:46 UTC, Hyacintholuscus commented on src/main/java/ru/practicum/workshop/reviewservice/service/ReviewServiceImpl.java
> +                if (label.equals(Label.LIKE)) {
Супер. А по поводу того, что деление на приватные труднее усваивается - тут, наверное, каждому своё. Но, когда читаешь тот большой блок кода, который был изначально, то можно потеряться в происходящем. А так ты сначала посмотрел: здесь происходит то, это и следующее. А потом уже подробнее рассматриваешь, что в приватных методах происходит

2024-11-26 13:55 UTC, Hyacintholuscus commented on src/main/java/ru/practicum/workshop/reviewservice/service/ReviewServiceImpl.java
> +            User evaluator = userStorage.findById(evaluatorId).orElseThrow(() -> {
Да, User в этом сервисе появился только из-за поля username, потому что при изменении отзыва, можно поменять и имя пользователя. Нам тогда говорили, что это как бы "публичное имя" и оно рассматривается отдельно от того, что в userService из 1 задачи. И, чтобы не было никаких проблем при изменении username, я решила выделить это в отдельную таблицу в БД.
По поводу того, чтобы оставить эту проверку: конкретно сейчас ты проверяешь только пользователей, которые сохранены в этом сервисе. А, когда нормальное взаимодействие будет настроено, то правильнее было бы это проверять как параметры авторизации. И смотреть на существование пользователя ещё до того, как его id попал в этот сервис. Поэтому я за то, чтобы убрать этот метод

2024-11-26 13:56 UTC, Hyacintholuscus commented on src/main/java/ru/practicum/workshop/reviewservice/controller/ReviewController.java
> +    public void addLike(@RequestHeader("X-Review-User-Id")
Как я и писала, это больше размышления, так что согласна

2024-11-26 14:07 UTC, Hyacintholuscus commented on src/test/java/ru/practicum/workshop/reviewservice/service/ReviewServiceImplTest.java
> +        assertEquals(0, review.getLikes());
Тут я имею в виду, что стоило бы записать в переменную количество лайков review, потом добавить и проверить, стало ли на 1 больше. А не так, чтобы тест упал из-за того, что у сущности не 0 лайков изначально (при том, что сущность в самом тесте не создаётся). Тест ведь работает, с тем, что есть на данный момент, а эта сущность может быть изменённой из-за других тестов, если она не создаётся каждый раз новая.
И соглашусь с тем, что иногда нужно использовать константы. Но не стоит ожидать, что переменная в сущности будет каким-то конкретным числом / объектом, если с этой сущностью ранее в тесте не было манипуляций по изменению этой переменной

2024-11-26 14:10 UTC, Hyacintholuscus commented on src/main/resources/application.properties
> +spring.sql.init.mode=always
Поделись со мной потом своими изысканиями тоже (ссылки можешь скинуть), потому что я не очень поняла, что конкретно тут происходит

2024-11-26 17:07 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/reviewservice/service/ReviewServiceImpl.java
> +            User evaluator = userStorage.findById(evaluatorId).orElseThrow(() -> {
Поправил с учётом обсуждения.

2024-11-26 17:07 UTC, KurakinPavel commented on src/main/resources/db/migration/V2__initial_schema.sql
> +    evaluator_id BIGINT REFERENCES users (id) ON DELETE SET NULL,
Поправил.

2024-11-26 17:08 UTC, KurakinPavel commented on src/main/java/ru/practicum/workshop/reviewservice/model/Opinion.java
> +    private User evaluator;
Исправил.

2024-11-26 17:08 UTC, KurakinPavel commented on src/test/java/ru/practicum/workshop/reviewservice/service/ReviewServiceImplTest.java
> +        assertEquals(0, review.getLikes());
Поправил в тестах.

2024-11-26 17:10 UTC, KurakinPavel commented on src/main/resources/application.properties
> +spring.sql.init.mode=always
Ок

2024-11-27 04:23 UTC, Hyacintholuscus approved these changes

2024-11-27 06:48 UTC, merged